# Generated by Django 5.0.4 on 2024-08-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.CharField(max_length=20, unique=True)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('department', models.CharField(max_length=100)),
                ('year_of_studying', models.IntegerField()),
            ],
        ),
    ]
